#!/usr/bin/env python

import ConfigParser
import optparse
import sys
import logging

from slack.api.client import OAuth2

if __name__ == '__main__':

    parser = optparse.OptionParser()

    parser.add_option('--config', dest='config', action='store', help='The path to a config file containing things like your Slack access token')
    parser.add_option('--channel', dest='channel', action='store', help='The Slack channel you want to post to')
    parser.add_option('--username', dest='username', action='store', help='The username you want to post to as')
    parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='be chatty (default is false)')
        
    options, args = parser.parse_args()

    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    cfg = ConfigParser.ConfigParser()
    cfg.read(options.config)

    api = OAuth2(cfg.get('slack', 'token'))

    message = ' '.join(args)

    args = {
        'channel': options.channel,
        'text': message
    }

    if (options.username):
        args['username'] = options.username

    try:
        rsp = api.execute_method('chat.postMessage', args)

    except Exception, e:
        logging.error("API call failed %s" % e)
        sys.exit(1)
